### PR TITLE
Fix inbound unfollow requests.

### LINKED ISSUE #71: Inbound Unfollow results in crash
Running latest Git version on Glitch.

I enabled logging via `LOGGING_ENABLED=true`.

I'm seeing that if I attempt to send an unfollow request from my Mastodon account `@andypiper@macaw.social` to `@andypiper@pipesmarks.glitch.me`, the Glitch app crashes with this logged:

```text
[2023-9-9 14:53:43] POST:/api/inbox 200 0.002ms
file:///app/src/routes/activitypub/inbox.js:75
  const name = req.body.object.replace(`https://${domain}/u/`, "");
                               ^
TypeError: req.body.object.replace is not a function
at handleUnfollow (file:///app/src/routes/activitypub/inbox.js:75:32)
at file:///app/src/routes/activitypub/inbox.js:254:18
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/index.js:346:12)
    at next (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/rbd/pnpm-volume/2c58c3bc-c846-4d1a-af35-475ee568b9ca/node_modules/express/lib/router/index.js:175:3)
```

### PR DESCRIPTION
**Pull request by pburke**
Fixes #71

### CODE REVIEW

File: src/routes/activitypub/inbox.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ async function handleUnfollow(req, res) {
 
   const myURL = new URL(req.body.actor);
   const targetDomain = myURL.hostname;
-  const name = req.body.object.replace(`https://${domain}/u/`, '');
+  const name = req.body.object.object.replace(`https://${domain}/u/`, '');
```
Comment (pburke) [inline src/routes/activitypub/inbox.js:69]: Assuming Mastodon is sending the right payload according to the ActivityPub spec, this fixes it for me.

**Review by ckolderup — APPROVED** [review]
yep, confirmed that the message from mastodon looks like:

```json
{
   "@context":"https://www.w3.org/ns/activitystreams",
   "id":"https://mastodon.social/users/redacted#follows/46650655/undo",
   "type":"Undo",
   "actor":"https://mastodon.social/users/redacted",
   "object":{
      "id":"https://mastodon.social/redacted",
      "type":"Follow",
      "actor":"https://mastodon.social/users/redacted",
      "object":"https://redacted.glitch.me/u/bookmarks"
   }
}
```

so we need the double-object. Thank you!
